site_name: extra-model Documentation
repo_url: https://github.com/wayfair-incubator/extra-model
repo_name: wayfair-incubator/extra-model
edit_uri: edit/main/docs/
docs_dir: docs
nav:
  - Overview: index.md
  - Running Extra: running_extra.md
  - Workflow: workflow.md
  - Examples: examples/examples.md
  - Using a Custom Base Class: custom_base_class.md
  - Blog: blog.md
  - RAM Requirements: ram_requirements.md
  #  - Reference: reference.md
  - Contributing:
      - Developer's Guide: contributing/developer_guide.md
      - Documentation: contributing/documentation.md
      - Publish a Release: contributing/publish_release.md
theme: material
plugins:
  - mkdocstrings:
      handlers:
        python:
          selection:
            docstring_style: "sphinx"
          rendering:
            heading_level: 3
            show_root_heading: True
            show_source: False
            show_root_full_path: False
